// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahksxziueqkacyaqtgeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoa3N4eml1ZXFrYWN5YXF0Z2V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMjAzMzUsImV4cCI6MjA2OTU5NjMzNX0.V3UV58ZhQPrsXanRKHZbbJdJq_smXvh4jtAC1cFK6tw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});